### PR TITLE
More complete version 

### PR DESCRIPTION
**Pull request by yhyu13**
Hi, Kunze

I saw your implementation of ThalNet repo which is very high-quality work. I tried to fix some minor issues and add my part into it. 

(1) There was only one major issue: the FF before GRU had num_outputs=self.output_size. I changed it to num_outputs=self.center_output_size (which is the same as center_size_per_module)
(2) I added MLP baseline.
(3) #1 is fixed by list() the second return argument of ThalNet.
(4) I posted my results in README.md

Have a good weekends!
Hang Yu, Oct14,2017

### CODE REVIEW

**Comment by juliuskunze** [comment]
Hey Hang Yu, thank you for your contribution, this is great!

Before I accept your pull request, would you mind cleaning up a bit (removing the mnist dataset files, .DS_Store files, files in tensorboard directory not needed for the readme)?

**Comment by yhyu13** [comment]
Hi, Julius

Sure thing! I am busy doing another thing, but I will let you know in the first place once it's done (It will be quick).

**Comment by yhyu13** [comment]
Hi, Julius

Nice! As you suggested, I've cleaned them up. But keep in mind that my code need to know the directory of mnist, you can find more in main.py->input_data.read_data_sets(...).

Regards,
Hang Yu

**Comment by juliuskunze** [comment]
Ok, thanks! Could you please also remove figure/.DS_Store and .DS_Store?

**Comment by yhyu13** [comment]
Done! I didn't realize that the existence of .DS_store, it was caused by "git add -A" which I used all the time (turns out it's a not so good practice).

**Comment by juliuskunze** [comment]
Alright, thank you!

**Pull request merged**
